on:
  push:
    branches:
      - "dev"

env:
  FLOWNAME: stoat
  IMAGE: zzstoatzz/flows:hello-ci-cd
  DEPLOYMENTYAML: ./prefect/flows/stoat.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build the image
        run: |
          docker build . --tag ${{ env.IMAGE }} -f ./prefect/Dockerfile

      - name: Login to registry
        env:
          CONTAINER_REGISTRY_USER: ${{secrets.CONTAINER_REGISTRY_USER}}
          CONTAINER_REGISTRY_PASSWORD: ${{secrets.CONTAINER_REGISTRY_PASSWORD}}
        run: |
          docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASSWORD 

      - name: Push to container registry
        run: docker push ${{ env.IMAGE }}

      - name: Pip update and install prefect
        run: pip install -U wheel pip prefect s3fs

      # - name: Prefect Cloud login
      #   run: |
      #     prefect config set PREFECT_API_KEY=$API_KEY
      #     prefect config set PREFECT_API_URL=$API_URL
      #   env:
      #     API_KEY: ${{ secrets.PREFECT_API_KEY }}
      #     API_URL: ${{ secrets.PREFECT_API_URL }}

      - name: Build Prefect deployment
        run: prefect deployment build ./prefect/flows/hello.py:$FLOWNAME -n $DEPLOYMENT_NAME -t $TAG -ib $INFRA -sb $STORAGE -o $DEPLOYMENTYAML -q $WORK_QUEUE
        env:
          DEPLOYMENT_NAME: hello-marvin
          TAG: dev
          INFRA: kubernetes-job/default-k8s-job
          STORAGE: s3/flow-script-storage
          WORK_QUEUE: "main"
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}

      - name: Apply Prefect deployment
        run: prefect deployment apply $DEPLOYMENTYAML

      - name: Summary of workflow
        run: echo Successfully created deployment and built image ${{ env.IMAGE }} >> $GITHUB_STEP_SUMMARY
      